<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\UrlService\HttpConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Services\UrlService\HttpConfig.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectManagementStudio.Model\ProjectManagementStudio.Model.csproj" />
    <ProjectReference Include="..\ProjectManagementStudio.ViewModel\ProjectManagementStudio.ViewModel.csproj" />
    <ProjectReference Include="..\ProjectManagementStudio.View\ProjectManagementStudio.View.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Services\UrlService\http.config.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
