<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.1.1" />
    <PackageReference Include="LiveCharts.Core" Version="0.9.8" />
    <PackageReference Include="LiveChartsCore" Version="2.0.0-rc5.4" />
    <PackageReference Include="LiveChartsCore.Behaviours" Version="2.0.0-rc5.4" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.0-rc5.4" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectManagementStudio.Model\ProjectManagementStudio.Model.csproj" />
  </ItemGroup>

</Project>
