<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.1.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc2" />
    <PackageReference Include="Xceed.Workbooks.NET" Version="3.0.25228.6154" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectManagementStudio.Model\ProjectManagementStudio.Model.csproj" />
  </ItemGroup>

</Project>
